### ISSUE TITLE
display problem with negative value

### ISSUE THREAD

**Issue by lelouar** [bhofmei/jbplugin-wigglesvg#1]
Hi,

I try to use you plugging it works for some track but with tracks with negative value the display have bug (not displaying negative values and sometaime even positive between 2 negative value).

The value of the track are displayed uppon mouse hover. 

version of Jbrowse : JBrowse 1.12.3

Thanks

**Comment by bhofmei** [comment]
Thank you for pointing this out. Can you attach a screenshot so I can see exactly what you mean with your samples?

**Comment by bhofmei** [comment]
Thanks again for pointing this out. I found the bug and it should be fixed. 
![image](https://user-images.githubusercontent.com/16089658/36384416-3544b52e-155d-11e8-9e7f-f5e8151b055c.png)

**Comment by lelouar** [comment]
Sorry, I don't have seen your post, it's nice that is being fixed.
